// <auto-generated />
using System;
using ChallengeIdwall.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChallengeIdwall.Migrations
{
    [DbContext(typeof(ChallengeDbContext.DataBaseContext))]
    [Migration("20231002023508_Oracle3")]
    partial class Oracle3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallengeIdwall.Model.FBIWantedResponse", b =>
                {
                    b.ToTable("FBI");
                });

            modelBuilder.Entity("ChallengeIdwall.Model.Fbi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SuspectId");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InterpolEntityId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SuspectTitle");

                    b.HasKey("Id");

                    b.HasIndex("InterpolEntityId");

                    b.ToTable("FBITable");
                });

            modelBuilder.Entity("ChallengeIdwall.Model.Interpol", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EntityId");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityId"));

                    b.Property<string>("Forename")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Forename");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Name");

                    b.Property<string>("Nationalities")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nationalities");

                    b.HasKey("EntityId");

                    b.ToTable("InterpolTable");
                });

            modelBuilder.Entity("ChallengeIdwall.Model.InterpolWantedResponse", b =>
                {
                    b.ToTable("Interpol");
                });

            modelBuilder.Entity("ChallengeIdwall.Model.Fbi", b =>
                {
                    b.HasOne("ChallengeIdwall.Model.Interpol", null)
                        .WithMany("fbis")
                        .HasForeignKey("InterpolEntityId");
                });

            modelBuilder.Entity("ChallengeIdwall.Model.Interpol", b =>
                {
                    b.Navigation("fbis");
                });
#pragma warning restore 612, 618
        }
    }
}
