// <auto-generated />
using ChallengeIdwall.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChallengeIdwall.Migrations
{
    [DbContext(typeof(ChallengeDbContext.DataBaseContext))]
    [Migration("20231002020425_OracleInicial")]
    partial class OracleInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallengeIdwall.Model.FBIWantedResponse", b =>
                {
                    b.ToTable("FBI");
                });

            modelBuilder.Entity("ChallengeIdwall.Model.Fbi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SuspectId");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SuspectTitle");

                    b.HasKey("Id");

                    b.ToTable("FBITable");
                });
#pragma warning restore 612, 618
        }
    }
}
